### ISSUE TITLE
Clarificaciones TP

### ISSUE THREAD

**Issue by maurosaquino** [octaviovillegas/TP_PROG3_1C_2018#1]
Profesor,

Tengo las siguientes dudas respecto al TP:

1) A los empleados se les asigna el rol al ingresar por dia o tienen un rol fijo? El login es por perfil o por usuario (se registra a cada usuario y se le asigna un perfil determinado o yo puedo ingresar con un rol y una contrasena y el nombre de usuario se guarda en un campo secundario)?
2) El cliente como accede a la encuesta y al estado del pedido? Se registra cada cliente como usuario del sitema? 
3) El punto #al mozo se le da un codigo de 5 caracteres al cliente que le permite identificar su pedido. A quien se le da el codigo al mozo o al cliente? Es el mismo codigo que se usa para identificar la mesa?
4) Tiene que haber algun tipo de correlacion entre la comida? Por ejemplo si se pide una milanesa y un vino, tiene que estar listo la milanesa para poder empezar la preparacion del vino?
5) Se puede pedir mas de un plato por mesa? en este caso todos los platos deben estar listos para que el estado general de la orden sea "listo para servir" (misma consulta respecto a los distintos pedidos) o se maneja item por item?
6) La foto como se saca? A efectos mecanicos de la aplicacion es un formulario donde se sube una imagen?
7) El menu es una seleccion fija de la carta? En este caso, cuantos items se deben agregar, cual es la posibilidad de cambiar guarniciones para un determinado plato o hacer algun cambio?
8) Que sucede si el tiempo estimado es mayor al tiempo que se indica por aplicacion?
9) Que se debe exportar a excel o pdf?
10) Los puntos 2,3,4 deben ser excluyentes entre si o deben funcionar en conjunto?

**Comment by octaviovillegas** [comment]
1- el perfil se le  pone  al dar de  alta. solo da de alta un socio.
2-tenes que leer  el enunciado en la sección que dice...   (# Las mesas tiene un código de identificación único de 5 caracteres...) , ahi esta tu respuesta.
3-En el BackEnd no te importa quien se lo da , simplemente lo tiene.
4-no
5-cada item esta listo para servir a distintos tiempos. y el  pedido puede tener varios items (milanesa con papas, cerveza, rabas , coca cola, vino tinto).
6-En el BackEnd no te importa , simplemente la pasas
7- existe el modificar en toda ítem.
8 - solo se muestra el tiempo.
9- todos los listados con titulo y descripción de los datos que muestra por ej:" listado de los 10 productos vas vendidos".
